rm -rf build
rm -rf prefix_sum_tree.egg-info
rm -rf dist
rm -rf prefix_sum_tree/__pycache__
rm -rf prefix_sum_tree/*.pyc
rm -rf prefix_sum_tree/experimental/__pycache__
rm -rf prefix_sum_tree/experimental/*.pyc
rm -rf test/__pycache__
rm -rf test/*.pyc
rm -rf .tox
rm -f prefix_sum_tree/*.so
rm -f prefix_sum_tree/src/_prefix_sum_tree.c
rm -f prefix_sum_tree/experimental/*.so
rm -f prefix_sum_tree/experimental/src/_prefix_sum_tree.cpp
rm -f prefix_sum_tree/experimental/src/_prefix_sum_tree.c
rm -f MANIFEST
